p1: p1.cpp
	g++ p1.cpp easycurses.cpp -l ncurses -o p1  
p2: 
	g++ p2.cpp easycurses.cpp -l ncurses -o p2
p3:

p4:

p5:

p6:


############### DON'T TOUCH BELOW ##################
run%: p%
	@./p$* || :

