part1:
	g++ part1.cpp -o part1	
part2: 
	g++ part2.cpp -o part2	
part3: 
	g++ part3.cpp -o part3		
part4: 
	g++ part4.cpp -o part4	
part5: 
	g++ part5.cpp -o part5

############### DON'T TOUCH BELOW ##################
run%: part%
	@./part$* || :

