p1: p1.cpp
	g++ p1.cpp easycurses.cpp -l ncurses -o p1  
p2: 
	g++ p2.cpp easycurses.cpp -l ncurses -o p2
p3:
	g++ p3.cpp easycurses.cpp -l ncurses -o p3
p4:
	g++ p4.cpp easycurses.cpp -l ncurses -o p4
p5:
	g++ p5.cpp easycurses.cpp -l ncurses -o p5
p6:
	g++ p6.cpp easycurses.cpp -l ncurses -o p6

############### DON'T TOUCH BELOW ##################
run%: p%
	@./p$* || :

